spring:
  application:
    name: Forum-Hub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/forum_hub}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  token:
    secret: ${JWT_SECRET:12345678}