spring:
  application:
    name: Forum-Hub
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
api:
  token:
    secret: ${JWT_SECRET:12345678}